_BASE_: "../Base-RCNN-FPN-COCOA_cls.yaml"
OUTPUT_DIR: /work/weientai18/aisformer/full_training_cocoa/
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_MASK_HEAD:
    NUM_CONV: 12
    POOLER_RESOLUTION: 14
    CUSTOM_NAME: AISFormer 
#SOLVER:
#  MAX_ITER: 20000
